# $(npm bin)/antora --clean --fetch antora-playbook.yml
# or
# $(npm bin)/antora --clean --generator=@antora/site-generator-ms --attribute=site-navigation-data-path=_/js/site-navigation-data.js --fetch antora-playbook.yml
site:
  title: Couchbase Docs Staging
  url: https://elated-villani-706182.netlify.app/
  start_page: home::index.adoc
  robots: disallow
  keys:
    nav_groups: |
      [
        { "title": "Server", "startPage": "home::server.adoc", "components": ["server"] },
        { "title": "Mobile", "startPage": "home::mobile.adoc", "components": ["couchbase-lite", "sync-gateway"] },
        { "title": "Cloud", "startPage": "cloud::index.adoc", "components": ["cloud"] },
        { "title": "Cloud-Native", "startPage": "cloud-native-database::index.adoc", "components": ["cloud-native-database"] },
        { "title": "Autonomous Operator", "components": ["operator"] },
        { "title": "Service Broker", "components": ["service-broker"] },
        { "title": "SDKs", "startPage": "home::sdk.adoc", "components": ["*-sdk", "cxx-txns", "elasticsearch-connector", "kafka-connector", "spark-connector"] },
        { "title": "Tutorials", "startPage": "tutorials::index.adoc", "components": ["tutorials"] }
      ]
git:
  ensure_git_suffix: false
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current
content:
  branches: master
  # NOTE the git@ segment in the URL indicates which repositories are private
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: https://git@github.com/couchbasecloud/couchbase-cloud
    branches: [main]
    start_path: docs/public
  - url: https://git@github.com/couchbase/docs-analytics
    branches: [release/7.0, release/6.6, release/6.5, release/6.0]
  - url: https://github.com/couchbase/couchbase-cli
    branches: [master, cheshire-cat, mad-hatter, 6.5.x-docs, alice]
    start_path: docs
  - url: https://git@github.com/couchbase/backup
    branches: [master, cheshire-cat, mad-hatter, 6.5.x-docs, alice]
    start_path: docs
  - url: https://github.com/couchbaselabs/cb-swagger
    branches: [release/7.0, release/6.6, release/6.5, release/6.0]
    start_path: docs
  # NOTE docs-server is currently after other server repos so nav key wins
  - url: https://github.com/couchbase/docs-server
    branches: [dev-reorg, release/6.6, release/6.5, release/6.0]
  - url: https://github.com/couchbase/docs-sdk-common
    branches: [release/7.0, release/6.6, release/6.5, release/6.0]
  - url: https://github.com/couchbase/docs-sdk-dotnet
    branches: [release/3.2, release/3.1, release/3.0, release/2.7]
  - url: https://github.com/couchbase/docs-sdk-java
    branches: [release/3.2, release/3.1, release/3.0, release/2.7]
  - url: https://github.com/couchbase/docs-sdk-nodejs
    branches: [release/3.2, release/3.1, release/3.0, release/2.6]
  - url: https://github.com/couchbase/docs-sdk-python
    branches: [release/3.2, release/3.1, release/3.0, release/2.5]
  - url: https://github.com/couchbase/docs-sdk-extensions
    branches: [main]
asciidoc:
  attributes:
    max-include-depth: 10
    page-partial: false
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    toc: ~
    xrefstyle: short
    enterprise: https://www.couchbase.com/products/editions[ENTERPRISE EDITION]
    community: https://www.couchbase.com/products/editions[COMMUNITY EDITION]
  extensions:
  - ./lib/asciidoctor-performance-patch.js
  - ./lib/source-url-include-processor.js
  - ./lib/json-config-ui-block-macro.js
  - ./lib/inline-man-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/tabs-block.js
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/prod-135/ui-bundle.zip
    #url: https://deploy-preview-xxx--cb-docs-ui.netlify.app/dist/ui-bundle.zip
    #snapshot: true
output:
  dir: ./public
